//! Checks audit records emitted by a realistic request sequence against the format
//! contract.
//!
//! The committed fixtures in `lakekeeper` pin the shape of the scenarios they cover, but a
//! fixture is generated by the test that asserts against it — so a wrongly built event
//! produces a fixture that agrees with it, and neither notices. This test instead states
//! rules that hold for *any* audit record and checks them against records produced by
//! going through the real service layer, which reaches paths no fixture exercises.
//!
//! It registers the audit listener on its own `ApiContext` only. The shared test harness
//! deliberately does not register it, so no other test is affected by this file.
//!
//! # This file is meant to grow
//!
//! The rules apply to any record, but only ever see records something emitted — so
//! coverage is exactly the request sequences exercised here, and that set starts small.
//! Widening it is the point: drive another call through `CatalogServer` and the existing
//! rules apply to whatever it produces. Reached today: the authorization family in both its
//! allowed and denied form, and the `idempotent_replay` family — which carries `action` and
//! `entity` but no `decision`, so it is the one record here that a consumer keying on
//! `entity` would misread. Not yet reached, cheapest to add first: views and table commits;
//! the plural `actions`/`entities` form, since every call here checks one action against one
//! entity; per-decision `id`/`for-principal`/`determined_by`, which need a batch-style check;
//! the operational family, which grant changes emit; and a real authorizer with an
//! authenticated actor (`AllowAllAuthorizer` and `random_request_metadata()` reach neither) —
//! the OpenFGA authorizer is the cheap way in, because CI already provisions it.
//!
//! Keep every test here on a current-thread runtime. Capture is thread-local:
//! `set_default` binds the subscriber to the calling thread, and the detached
//! `tokio::spawn` that dispatches audit events has to be polled on that thread to be seen.
//! A second `#[sqlx::test]` is fine — `sqlx_core::rt::test_block_on` builds a fresh
//! `Builder::new_current_thread()` runtime per invocation and cargo runs each test on its
//! own thread, so there is nothing shared to contend for. What breaks capture is
//! `flavor = "multi_thread"`, which lets the dispatch task run on a worker thread that has
//! no default subscriber. `EXPECTED_RECORDS` is what catches that: capture would go to
//! zero, or to some subset, and a count has to be met where "did anything arrive" does not.
//!
//! Adding a case is cheap, and it is two steps: drive another call through `CatalogServer`
//! or `ApiServer` before the wait, and raise `EXPECTED_RECORDS` by however many records it
//! emits. The existing rules then apply to whatever it produced. Run it on its own with
//! `just test-audit-corpus`, which needs the local Postgres from the initial setup — the
//! count is checked there in seconds, so there is no reason to learn about it from CI.
//!
//! A good case is one that reaches a code path no other case here reaches — a new assertion
//! is worth less than a new record shape, because the rules are already general and it is
//! the inputs that are narrow.
//!
//! If you are here because you changed the audit log format, see the audit log section of
//! `docs/docs/developer-guide.md`: extending this file is part of that change.

use std::sync::Arc;

use iceberg::NamespaceIdent;
use lakekeeper::{
    api::iceberg::v1::{
        DataAccess, NamespaceParameters, namespace::NamespaceService as _,
        tables::TablesService as _,
    },
    server::CatalogServer,
    service::{
        authz::AllowAllAuthorizer,
        events::backends::audit::{AuditEventListener, contract},
        idempotency::IdempotencyKey,
    },
};
use lakekeeper_integration_tests::{
    SetupTestCatalog, create_table_request, memory_io_profile, random_request_metadata,
};

/// How many audit records the request sequence in the test below emits.
///
/// **Adding or removing a call means updating this number**, and nothing but a failing test
/// will tell you.
///
/// What this cannot do: prove that no *further* record arrives. After the count is reached
/// the test watches for [`SETTLE_WINDOW`] and warns if more turn up, but a record emitted
/// later than that is invisible to it. So the constant is a reliable floor and only a
/// best-effort ceiling.
const EXPECTED_RECORDS: usize = 10;

/// How long to wait for [`EXPECTED_RECORDS`] before failing.
///
/// Generous on purpose: it is reached only when the test is already failing, so a large
/// value costs nothing on a green run and buys tolerance on a loaded machine.
const CAPTURE_DEADLINE: std::time::Duration = std::time::Duration::from_secs(10);

/// How often to re-read while waiting. Short, because each poll is a cheap buffer read and
/// the `await` is what lets the detached dispatch tasks run at all.
const POLL_INTERVAL: std::time::Duration = std::time::Duration::from_millis(25);

/// How long to keep watching after the expected count arrives, to notice an extra record.
///
/// A warning, not a failure: an extra record is not a contract violation — it is checked by
/// the same rules as the others — it just means [`EXPECTED_RECORDS`] is stale.
const SETTLE_WINDOW: std::time::Duration = std::time::Duration::from_millis(250);
use sqlx::PgPool;

#[derive(Clone, Default)]
struct CapturedLogs(Arc<std::sync::Mutex<Vec<u8>>>);

impl std::io::Write for CapturedLogs {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.0.lock().expect("log buffer poisoned").extend(buf);
        Ok(buf.len())
    }
    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

impl tracing_subscriber::fmt::MakeWriter<'_> for CapturedLogs {
    type Writer = Self;
    fn make_writer(&self) -> Self::Writer {
        self.clone()
    }
}

/// Every audit record captured so far, envelope fields stripped.
fn audit_records(logs: &CapturedLogs) -> Vec<serde_json::Value> {
    let bytes = logs.0.lock().expect("log buffer poisoned").clone();
    String::from_utf8(bytes)
        .expect("log output is utf-8")
        .lines()
        .filter_map(|line| serde_json::from_str::<serde_json::Value>(line).ok())
        .filter(|record| record.get("event_source").and_then(|v| v.as_str()) == Some("audit"))
        .map(contract::contract_fields)
        .collect()
}

#[sqlx::test]
async fn audit_records_from_a_real_request_sequence_satisfy_the_contract(pool: PgPool) {
    let logs = CapturedLogs::default();
    // Thread-local, not global: `sqlx::test` runs on a current-thread runtime, so the
    // detached `tokio::spawn` that dispatches audit events is polled on this same thread
    // and sees this subscriber. A global subscriber would race with other test binaries.
    // Mirrors the binary's formatter so the captured records are shaped like production's.
    let _guard = tracing::subscriber::set_default(
        tracing_subscriber::fmt()
            .json()
            .flatten_event(true)
            .with_current_span(false)
            .with_span_list(true)
            .with_writer(logs.clone())
            .finish(),
    );

    let (ctx, warehouse_response) = SetupTestCatalog::builder()
        .pool(pool.clone())
        .storage_profile(memory_io_profile())
        .authorizer(AllowAllAuthorizer::default())
        .number_of_warehouses(1)
        .build()
        .setup()
        .await;

    // Only this context emits audit events; the shared harness is untouched.
    ctx.v1_state
        .events
        .append(Arc::new(AuditEventListener))
        .await;

    let warehouse = warehouse_response.warehouse_id.to_string();
    let namespace = NamespaceIdent::from_vec(vec!["audit_corpus".to_string()]).unwrap();

    // A create that succeeds, then a lookup of something absent so a genuine denial or
    // not-found path is exercised too.
    let _ = CatalogServer::create_namespace(
        Some(warehouse.clone().into()),
        iceberg_ext::catalog::rest::CreateNamespaceRequest {
            namespace: namespace.clone(),
            properties: Some(std::collections::HashMap::from([(
                "owner".to_string(),
                "audit-corpus".to_string(),
            )])),
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    let namespace_params = NamespaceParameters {
        prefix: Some(warehouse.clone().into()),
        namespace: namespace.clone(),
    };

    // A table, which reaches the `create_table` action and its `name` / `table_id` context.
    let created = CatalogServer::create_table(
        namespace_params.clone(),
        create_table_request(Some("audited_table".to_string()), None),
        DataAccess::not_specified(),
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // A table created, then dropped twice under one Idempotency-Key. Three things this
    // reaches that nothing else here does: an authorization record with a POPULATED
    // `idempotency_key` (every other record in this corpus, and every committed fixture, has
    // it null), and the `idempotent_replay` family, which carries `action` and `entity` but
    // no `decision`. The drop endpoint checks idempotency before authorizing, so the replayed
    // call emits the replay record alone.
    // A key is globally unique, not per endpoint: reusing one across two operations is
    // rejected with `IdempotencyKeyReused`, so the create and the drop get their own.
    let new_key = || {
        IdempotencyKey::parse(&uuid::Uuid::now_v7().to_string())
            .expect("a v7 uuid is a valid idempotency key")
    };
    let keyed_metadata = |key| {
        let mut metadata = random_request_metadata();
        metadata.with_idempotency_key(key);
        metadata
    };
    let drop_key = new_key();
    let replayed_table = || lakekeeper::api::iceberg::v1::TableParameters {
        prefix: Some(warehouse.clone().into()),
        table: iceberg::TableIdent::new(namespace.clone(), "replayed_table".to_string()),
    };
    let drop_params = || lakekeeper::api::iceberg::v1::DropParams {
        purge_requested: true,
        force: false,
    };

    let replayed_created = CatalogServer::create_table(
        namespace_params.clone(),
        create_table_request(Some("replayed_table".to_string()), Some(false)),
        DataAccess::not_specified(),
        ctx.clone(),
        keyed_metadata(new_key()),
    )
    .await;

    if replayed_created.is_ok() {
        let _ = CatalogServer::drop_table(
            replayed_table(),
            drop_params(),
            ctx.clone(),
            keyed_metadata(drop_key),
        )
        .await;

        let _ = CatalogServer::drop_table(
            replayed_table(),
            drop_params(),
            ctx.clone(),
            keyed_metadata(drop_key),
        )
        .await;
    }

    // Loading it reaches `get_metadata` on an entity that carries a table id and location,
    // rather than only a namespace.
    let _ = CatalogServer::load_table(
        lakekeeper::api::iceberg::v1::TableParameters {
            prefix: Some(warehouse.clone().into()),
            table: iceberg::TableIdent::new(namespace.clone(), "audited_table".to_string()),
        },
        lakekeeper::api::iceberg::v1::tables::LoadTableRequest::builder().build(),
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // Listing reaches an action whose entity is the namespace but whose result is a set.
    // It still emits the singular `entity` form: arity follows the entities checked, not
    // the rows returned.
    let _ = CatalogServer::list_tables(
        namespace_params.clone(),
        lakekeeper::api::iceberg::v1::ListTablesQuery {
            page_token: lakekeeper::api::iceberg::v1::PageToken::NotSpecified,
            page_size: None,
            return_uuids: true,
            return_protection_status: false,
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // Property updates carry `updated-properties` and `removed-properties`, the two
    // hyphenated action context fields.
    let _ = CatalogServer::update_namespace_properties(
        namespace_params.clone(),
        iceberg_ext::catalog::rest::UpdateNamespacePropertiesRequest {
            removals: Some(vec!["owner".to_string()]),
            updates: Some(std::collections::HashMap::from([(
                "retention".to_string(),
                "30d".to_string(),
            )])),
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // A drop with purge, which carries the `purge` context field.
    if created.is_ok() {
        let _ = CatalogServer::drop_table(
            lakekeeper::api::iceberg::v1::TableParameters {
                prefix: Some(warehouse.clone().into()),
                table: iceberg::TableIdent::new(namespace.clone(), "audited_table".to_string()),
            },
            lakekeeper::api::iceberg::v1::DropParams {
                purge_requested: true,
                force: false,
            },
            ctx.clone(),
            random_request_metadata(),
        )
        .await;
    }

    // Finally a lookup of something absent, so a genuine denial is in the corpus too.
    let _ = CatalogServer::namespace_exists(
        NamespaceParameters {
            prefix: Some(warehouse.clone().into()),
            namespace: NamespaceIdent::from_vec(vec!["does_not_exist".to_string()]).unwrap(),
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // Wait for the expected number rather than for a fixed interval. See EXPECTED_RECORDS.
    let deadline = std::time::Instant::now() + CAPTURE_DEADLINE;
    let mut records = audit_records(&logs);
    while records.len() < EXPECTED_RECORDS && std::time::Instant::now() < deadline {
        tokio::time::sleep(POLL_INTERVAL).await;
        records = audit_records(&logs);
    }

    assert!(
        records.len() >= EXPECTED_RECORDS,
        "expected {EXPECTED_RECORDS} audit records from this request sequence, captured \
         {} within {CAPTURE_DEADLINE:?}.\n\n\
         If you ADDED a call above, or one you added emits more than you thought: raise \
         EXPECTED_RECORDS to match. If you REMOVED a call: lower it. The constant is the \
         only thing that notices a request silently stopping emitting, so it has to be \
         maintained by hand — see its doc comment.\n\n\
         If you changed neither, this is the real failure the constant exists to catch: \
         something that used to emit an audit record no longer does. Capture can also \
         fail wholesale — a listener not registered on this context, or a runtime that \
         is not current-thread (see this file's header).\n\n\
         What did arrive:\n{}",
        records.len(),
        describe(&records),
    );

    // Everything expected is here. Keep watching briefly: an extra record means the count
    // above is stale, and it is better to hear about it than to have it pass unmentioned.
    tokio::time::sleep(SETTLE_WINDOW).await;
    let settled = audit_records(&logs);
    if settled.len() > EXPECTED_RECORDS {
        eprintln!(
            "\n!! audit corpus: WARNING — {} record(s) arrived, EXPECTED_RECORDS says \
             {EXPECTED_RECORDS}. The extra ones are checked below, so nothing is wrong with \
             the contract, but the constant is stale: raise it to {}. Extras that arrive \
             later than {SETTLE_WINDOW:?} are not detected at all, so treat this as a \
             lower bound.\n{}\n",
            settled.len(),
            settled.len(),
            describe(&settled),
        );
    }
    let records = settled;

    for (index, record) in records.iter().enumerate() {
        contract::assert_satisfies(record, &format!("record {index}"));
    }

    eprintln!("audit corpus: {} record(s) checked", records.len());
}

/// One line per record, enough to tell which call produced it. For failure messages: a raw
/// dump of seven full records buries the one thing the reader needs, which is what is missing.
fn describe(records: &[serde_json::Value]) -> String {
    records
        .iter()
        .enumerate()
        .map(|(index, record)| {
            let field = |name: &str| {
                record
                    .get(name)
                    .and_then(serde_json::Value::as_str)
                    .unwrap_or("-")
                    .to_string()
            };
            let action = record
                .get("action")
                .and_then(|action| action.get("action_name"))
                .and_then(serde_json::Value::as_str)
                .unwrap_or("-");
            format!(
                "  {index}: action={action} decision={} operation={}",
                field("decision"),
                field("operation"),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}
