name: Unittests

on:
  push:
    branches:
      - main
      - "manual-release-*"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.84

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  sqlx-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Cargo sqlx-check
        run: |
          export DEBIAN_FRONTEND=noninteractive 
          sudo apt-get update && sudo apt-get install -yqq libpq-dev --no-install-recommends
          cargo install -q --version=0.8.2 sqlx-cli --no-default-features --features postgres
          cargo sqlx prepare --check --workspace -- --all-features

  check-format:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo snap install --edge --classic just
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: ${{ env.RUST_TOOLCHAIN }},nightly
        env:
          RUST_CACHE_KEY_OS: rust-${{ env.RUST_TOOLCHAIN }}-cache-ubuntu-24.04

      - name: Cargo format
        run: just check-format

      - name: Check diff
        run: git diff --exit-code

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          sudo snap install --edge --classic just

      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: ${{ env.RUST_TOOLCHAIN }}
        env:
          RUST_CACHE_KEY_OS: rust-${{ env.RUST_TOOLCHAIN }}-cache-ubuntu-24.04
          TEST_OPENFGA: 1
          TEST_AZURE: 1
          TEST_AWS: 1
          TEST_GCS: 1
          TEST_KV2: 1
          TEST_MINIO: 1

      - name: Cargo clippy
        run: just check-clippy
        env:
          RUST_CACHE_KEY_OS: rust-${{ env.RUST_TOOLCHAIN }}-cache-ubuntu-24.04
          TEST_OPENFGA: 1
          TEST_AZURE: 1
          TEST_AWS: 1
          TEST_GCS: 1
          TEST_KV2: 1
          TEST_MINIO: 1

  check-generated-cotents-match:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          sudo snap install --edge --classic just
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: ${{ env.RUST_TOOLCHAIN }}
        env:
          RUST_CACHE_KEY_OS: rust-${{ env.RUST_TOOLCHAIN }}-cache-ubuntu-24.04
      - name: Regenerate management openapi
        run: just update-management-openapi
      - name: Fail on diff
        run: git diff -I ".*version.*" -w --ignore-blank-lines --exit-code Cargo.lock docs/docs/api/
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build TS Client
        run: npx @hey-api/openapi-ts -i docs/docs/api/management-open-api.yaml -o src/gen/management -c @hey-api/client-fetch

  test:
    runs-on: ubuntu-24.04
    services:
      vault:
        image: hashicorp/vault:latest
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: myroot
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
        options: >-
          --health-cmd "vault status -address http://localhost:8200"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: minio-root-user
          MINIO_ROOT_PASSWORD: minio-root-password
          MINIO_API_PORT_NUMBER: 9000
          MINIO_CONSOLE_PORT_NUMBER: 9001
          MINIO_SCHEME: http
          MINIO_DEFAULT_BUCKETS: tests
        volumes:
          - ${{ github.workspace }}/data:/data
        ports:
          - 9000:9000
          - 9001:9001
        options: --health-cmd "curl -I http://localhost:9000/minio/health/live"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        env:
          RUST_CACHE_KEY_OS: rust-${{ env.RUST_TOOLCHAIN }}-cache-ubuntu-24.04

      - name: Setup cargo nextest
        run: cargo install --force cargo-nextest

      - name: Setup cargo nextest
        run: cargo install cargo-nextest

      - name: Migrate database
        run: |
          export DEBIAN_FRONTEND=noninteractive 
          sudo apt-get update && sudo apt-get install -yqq libpq-dev --no-install-recommends
          cargo install -q --version=0.8.2 sqlx-cli --no-default-features --features postgres
          cd crates/iceberg-catalog
          sqlx database create
          sqlx migrate run
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      - name: Setup vault
        run: |
          export VAULT_ADDR=http://localhost:8200
          export DEBIAN_FRONTEND=noninteractive 
          sudo apt update && sudo apt install gpg wget
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

          vault login -address "${VAULT_ADDR}" myroot
          vault auth  enable -address "${VAULT_ADDR}"  userpass
          echo "path \"secret/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] }" > /tmp/app.hcl
          vault policy write -address "${VAULT_ADDR}" app /tmp/app.hcl
          vault write -address "${VAULT_ADDR}" auth/userpass/users/test password=test policies=app

      - name: Setup openfga
        run: docker run -d -p 35081:8081 openfga/openfga:v1.6 run

      - name: Test
        run: cargo nextest run --profile ci --all-targets --all-features --workspace
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          TEST_KV2: 1
          LAKEKEEPER_TEST__KV2__URL: http://localhost:8200
          LAKEKEEPER_TEST__KV2__USER: test
          LAKEKEEPER_TEST__KV2__PASSWORD: test
          LAKEKEEPER_TEST__KV2__SECRET_MOUNT: secret
          # minio test envs
          TEST_MINIO: 1
          LAKEKEEPER_TEST__S3_BUCKET: tests
          LAKEKEEPER_TEST__S3_REGION: local
          LAKEKEEPER_TEST__S3_ACCESS_KEY: minio-root-user
          LAKEKEEPER_TEST__S3_SECRET_KEY: minio-root-password
          LAKEKEEPER_TEST__S3_ENDPOINT: http://localhost:9000

          TEST_OPENFGA: 1
          LAKEKEEPER_TEST__OPENFGA__ENDPOINT: http://localhost:35081

          TEST_AZURE: ${{ secrets.TEST_AZURE }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_FILESYSTEM: ${{ secrets.AZURE_STORAGE_FILESYSTEM }}
          AZURE_STORAGE_SHARED_KEY: ${{ secrets.AZURE_STORAGE_SHARED_KEY }}

          TEST_AWS: ${{ secrets.TEST_AWS }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_S3_STS_ROLE_ARN: ${{ secrets.AWS_S3_STS_ROLE_ARN }}

          TEST_GCS: ${{ secrets.TEST_GCS }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GCS_CREDENTIAL: ${{ secrets.GCS_CREDENTIAL }}
      - name: Upload junit
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: target/nextest/ci/junit.xml
      - name: Doc Test
        run: cargo test --no-fail-fast --doc --all-features --workspace
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
